package com.gaitvision

import androidx.compose.ui.window.ComposeUIViewController
import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.gaitvision.data.AppDatabase
import com.gaitvision.platform.IOSPoseDetector
import com.gaitvision.platform.IOSVideoProcessor
import platform.Foundation.NSHomeDirectory

fun MainViewController() = ComposeUIViewController {
    // Database setup for iOS
    val dbFilePath = NSHomeDirectory() + "/gaitvision.db"
    val db = Room.databaseBuilder<AppDatabase>(
        name = dbFilePath,
        factory = { AppDatabase_Impl() } // Generated by KSP
    ).setDriver(BundledSQLiteDriver())
     .build()

    App(
        poseDetector = IOSPoseDetector(),
        videoProcessor = IOSVideoProcessor(),
        database = db
    )
}
